apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: <%= appName %>
  namespace: default
  labels:
    team: <%= team %>
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 6
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 768Mi
  vault:
    enabled: false
  ingresses:
    - "https://<%= appName %>.nais.adeo.no"
  webproxy: true